<form id="form-tipo-saida" class="form-validate" action="<?=$url_action?>" method="POST">
    <input type="hidden" name="csrf" value="<?=$csrf?>">
    <?php if (!empty($tipoSaida->id)) : ?>
        <input type="hidden" name="id" value="<?=$tipoSaida->hash()?>">
    <?php endif ?>

    <div class="mb-3">
        <label for="descricao" class="form-label" title="Campo Obrigatório">Descrição <span class="text-danger">*</span></label>
        <input type="text" class="form-control" id="descricao" name="descricao" placeholder="Ex: Venda, Abate, Transferência, Descarte" required value="<?=$tipoSaida->descricao ?? ""?>">
    </div>
</form>
