<form id="form-motivo-tratamento" class="form-validate" action="<?=$url_action?>" method="POST">
    <input type="hidden" name="csrf" value="<?=$csrf?>">
    <?php if (!empty($motivoTratamento->id)) : ?>
        <input type="hidden" name="id" value="<?=$motivoTratamento->hash()?>">
    <?php endif ?>

    <div class="mb-3">
        <label for="descricao" class="form-label" title="Campo Obrigatório">Descrição <span class="text-danger">*</span></label>
        <input type="text" class="form-control" id="descricao" name="descricao" placeholder="Ex: Vacinação de Rotina, Vermifugação, Tratamento Clínico" required value="<?=$motivoTratamento->descricao ?? ""?>">
    </div>
</form>
