<form id="form-tipo-dieta" class="form-validate" action="<?=$url_action?>" method="POST">
    <input type="hidden" name="csrf" value="<?=$csrf?>">
    <?php if (!empty($tipo->id)) : ?>
        <input type="hidden" name="id" value="<?=$tipo->hash()?>">
    <?php endif ?>

    <div class="mb-3">
        <label for="descricao" class="form-label" title="Campo Obrigatório">Descrição <span class="text-danger">*</span></label>
        <input type="text" class="form-control" id="descricao" name="descricao" placeholder="Ex: Total, Trato, Suplemento, Pré-mistura, Núcleo, Concentrado" required value="<?=$tipo->descricao ?? ""?>">
    </div>
</form>
